version: '3.8'

services:
  animal-shelter-frontend:
    build: .
    container_name: animal-shelter-frontend
    networks:
      - animal-shelter
    args:
      - BASE_URL=${BASE_URL}

networks:
  animal-shelter:
    name: animal-shelter
    external: true