version: '3.8'

services:
  animal-shelter-frontend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - BASE_URL=${BASE_URL}
    container_name: animal-shelter-frontend
    networks:
      - animal-shelter
      

networks:
  animal-shelter:
    name: animal-shelter
    external: true