version: '3.8'
name: ${NAME}

services:
  animal-shelter-frontend:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - BASE_URL=${BASE_URL}
    networks:
      - animal-shelter
      

networks:
  animal-shelter:
    name: ${NETWORK}
    external: true