name: Server Deploy

on: 
  push:
    branches: [dev]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      BASE_URL: https://dev.pawparadise24.de/api
      NAME: dev
      NETWORK: animal-shelter-dev
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          ref: dev
      - name: Build Images
        run: docker compose up -d --build