name: Server Deploy

on: 
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    env:
      BASE_URL: https://www.pawparadise24.de/api
      CONTAINER_NAME: animal-shelter-frontend
      NETWORK: animal-shelter
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Images
        run: docker compose up -d --build