name: Server Deploy

on: 
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps: 
      - name: Build Images
        run: docker compose -f docker-compose.yml down
      - name: Build Images
        run: docker compose -f docker-compose.yml up -d --build
