name: Server Deploy

on: 
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: [self-hosted, Linux, x64]
    steps: 
      - name: Build Images
        run: docker compose down
      - name: Build Images
        run: docker compose up -d --build
